### ISSUE TITLE
Issue with Apache as reverse proxy

### ISSUE THREAD

**Issue by mihha** [activepieces/activepieces#3429]
**Describe the bug**
I have a problem running Activepiecese (latest version) in a docker compose instalaltion, behind the Apache web server, which is acting as a reverse proxy. I saw your documentation about Nginx reverse proxy configuration (https://www.activepieces.com/docs/install/setup-ssl#setup-nginx) and following it, I tried to convert Nginx rules to the Apache rules like this

**Nginx**
```
proxy_pass http://localhost:8080;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection 'upgrade';
proxy_set_header Host $host;
proxy_cache_bypass $http_upgrade;   
```

**Apache**
```
RewriteEngine on
RewriteCond %{HTTP:Connection} Upgrade [NC]
RewriteCond %{HTTP:Upgrade} websocket [NC]
RewriteRule /(.*) ws://127.0.0.1:28080/$1 [P,L]

ProxyPreserveHost On

ProxyPass / http://localhost:28080/ flushpackets=on
ProxyPassReverse / http://localhost:28080/

<Proxy *>
    allow from all
</Proxy>

ProxyRequests Off
```

I can access activepieces backend, but if I add some (for example) trigger to the Flow, I get this in the browser error console
![image](https://github.com/activepieces/activepieces/assets/3791124/deb77320-8bce-4aee-90f7-90b19399683c)

No idea what could be wrong or missing here

Can you please provide some guidelines about the errors and possibly how to resolve them?

**Comment by abuaboud** [comment]
If you open any of these pages, does it show 404 page with graphics, or just plain text, so we can verify if it reaches the frontend or the backend

**Comment by mihha** [comment]
Hi,

thank you for writing back

If I try to access one of the links, for example this one:

`https://MY_DOMAIN/api/v1/pieces/%40activepieces%2Fpiece-imap?version=~0.2.3&edition=ce`

I get the following
![image](https://github.com/activepieces/activepieces/assets/3791124/d3e6d5a8-4e92-40b6-908a-941bd4dc26cd)

**Comment by abuaboud** [comment]
Something odd in Apache configuration it shows port 28080, Is that correct?

And which configuration currently are you using?

**Comment by mihha** [comment]
Hi,

yes, port 28080 is correct because I have created my docker-compose file to expose port 28080 externally and NAT it to the port 80 internally

Here is the whole docker-compose.yml file

```
version: '3.0'
services:
  activepieces:
    image: activepieces/activepieces:0.9.0
    container_name: activepieces
    restart: unless-stopped
    ## Enable the following line if you already use AP_EXECUTION_MODE with SANDBOXED or old activepieces, checking the breaking change documentation for more info.
    ## privileged: true
    ports:
      - '28080:80'
    depends_on:
      - postgres
      - redis
    env_file: .env
    networks:
      - activepieces
  postgres:
    image: 'postgres:14.4'
    container_name: postgres
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=${AP_POSTGRES_DATABASE}'
      - 'POSTGRES_PASSWORD=${AP_POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${AP_POSTGRES_USERNAME}'
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    networks:
      - activepieces
  redis:
    image: 'redis:7.0.7'
    container_name: redis
    restart: unless-stopped
    volumes:
      - './redis_data:/data'
    networks:
      - activepieces
networks:
  activepieces:
```

Here is also the whole Apache virtual host configuration

```
SuexecUserGroup "#1002" "#1002"
ServerName activepieces.mihha-hosting.com
ServerAlias www.activepieces.mihha-hosting.com
ServerAlias mail.activepieces.mihha-hosting.com
ServerAlias webmail.activepieces.mihha-hosting.com
ServerAlias admin.activepieces.mihha-hosting.com
DocumentRoot /home/mihha-hosting/domains/activepieces.mihha-hosting.com/public_html
ErrorLog /var/log/virtualmin/activepieces.mihha-hosting.com_error_log
CustomLog /var/log/virtualmin/activepieces.mihha-hosting.com_access_log combined

ProxyPass /.well-known !
RewriteEngine on
RewriteCond %{HTTP_HOST} =webmail.activepieces.mihha-hosting.com
RewriteRule ^(?!/.well-known)(.*) https://activepieces.mihha-hosting.com:20000/ [R]
RewriteCond %{HTTP_HOST} =admin.activepieces.mihha-hosting.com
RewriteRule ^(?!/.well-known)(.*) https://activepieces.mihha-hosting.com:10000/ [R]


#Start of Activepieces configuration

RewriteCond %{HTTP:Connection} Upgrade [NC]
RewriteCond %{HTTP:Upgrade} websocket [NC]
RewriteRule /(.*) ws://127.0.0.1:28080/$1 [P,L]

ProxyPreserveHost On

ProxyPass / http://localhost:28080/ flushpackets=on
ProxyPassReverse / http://localhost:28080/

<Proxy *>
    allow from all
</Proxy>

ProxyRequests Off

#End of Activepieces configuration


SSLEngine on
SSLCertificateFile /home/mihha-hosting/domains/activepieces.mihha-hosting.com/ssl.cert
SSLCertificateKeyFile /home/mihha-hosting/domains/activepieces.mihha-hosting.com/ssl.key
SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
SSLCACertificateFile /home/mihha-hosting/domains/activepieces.mihha-hosting.com/ssl.ca
IPCCommTimeout 31
Protocols http/1.1
```
