### ISSUE TITLE
Encountered an error : ActivepiecesError: SYSTEM_PROP_NOT_DEFINED: System property AP_POSTGRES_HOST is not defined, please check the documentation

### ISSUE THREAD

**Issue by topmask** [activepieces/activepieces#3466]
ActivepiecesError: SYSTEM_PROP_NOT_DEFINED: System property AP_POSTGRES_HOST is not defined, please check the documentation
    at Object.getOrThrow (webpack:///src/app/helper/system/system.ts:88:19)
    at createPostgresDataSource (webpack:///src/app/database/postgres-connection.ts:242:25)
    at Array.Object.defineProperty.value (webpack:///src/app/database/database-connection.ts:124:35)
    at __webpack_require__ (webpack:///webpack/bootstrap:19:1)
    at <anonymous> (webpack:///src/main.ts:3:1)
    at <anonymous> (webpack:///src/main.ts:102:50)
    at Object.<anonymous> (webpack:///src/main.ts:102:50)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32) {
  error: {
    code: 'SYSTEM_PROP_NOT_DEFINED',
    params: { prop: 'POSTGRES_HOST' }
  }
}

Node.js v18.17.1

docker-compose.yml

```

version: '3.0'
services:
  activepieces:
    image: activepieces/activepieces:0.14.3
    container_name: activepieces
    restart: unless-stopped
    ## privileged: true
    ports:
      - '127.0.0.1:8888:80'
    depends_on:
      - postgres
      - redis
    env_file: .env
    networks:
      - activepieces
  postgres:
    image: 'postgres:14.4'
    container_name: postgres
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=${AP_POSTGRES_DATABASE}'
      - 'POSTGRES_PASSWORD=${AP_POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${AP_POSTGRES_USERNAME}'
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    networks:
      - activepieces
  redis:
    image: 'redis:7.0.7'
    container_name: redis
    restart: unless-stopped
    volumes:
      - './redis_data:/data'
    networks:
      - activepieces
volumes:
  postgres_data:
  redis_data:
networks:
  activepieces:


```

.env
```
AP_POSTGRES_DATABASE=abc
AP_POSTGRES_PASSWORD=xxx
AP_POSTGRES_USERNAME=aaa
```
