### ISSUE TITLE
[BUG]: Upgrading from 0.19.0 to 0.20.0 failed.

### ISSUE THREAD

**Issue by MrMYHuang** [activepieces/activepieces#3933]
**Describe the bug**

I set up my activepieces in a docker-compose.yml file, like this:

```
# ...

    activepieces:
      image: activepieces/activepieces:0.19.0
      privileged: true
      ports:
        - 8892:80
      volumes:
        - ~/.activepieces:/root/.activepieces
      environment:
        - AP_QUEUE_MODE=MEMORY
        - AP_EXECUTION_MODE=SANDBOXED
        - AP_SIGN_UP_ENABLED=true
        - AP_DB_TYPE=SQLITE3
        - AP_TRIGGER_DEFAULT_POLL_INTERVAL=1
        - AP_CLOUD_AUTH_ENABLED=true
        - AP_WEBHOOK_TIMEOUT_SECONDS=300
        - AP_FRONTEND_URL=https://activepieces.example.com
      networks:
        - backend
       
# ...
```
This worked well. However, after I update the activepieces version from 0.19.0 to 0.20.0 in docker-compose.yml, then I execute `docker-compose up -d,` activepieces 0.20.0 fails to start with the following errors:

```
Migration "AddTriggerTestStrategy1707087022764" failed, error: Cannot create property 'testStrategy' on string '{'
{"level":30,"time":1707990507451,"pid":8,"hostname":"3f7c9e1d2e37","msg":"RemoveFlowInstanceSqlite1702412280963 up"}
{"level":30,"time":1707990507459,"pid":8,"hostname":"3f7c9e1d2e37","msg":"UpdateStatusInUserSqlite1703713027818 up"}
{"level":30,"time":1707990507483,"pid":8,"hostname":"3f7c9e1d2e37","msg":"RenameAppNameToPieceNameSqlite1703713475755 up"}
{"level":50,"time":1707990507530,"pid":8,"hostname":"3f7c9e1d2e37","err":{"type":"TypeError","message":"Cannot create property 'testStrategy' on string '{'","stack":"TypeError: Cannot create property 'testStrategy' on string '{'\n    at pieceMetadata (webpack:///src/app/database/migration/common/1707087022764-add-trigger-test-strategy.ts:51:17)\n    at AddTriggerTestStrategy1707087022764.<anonymous> (webpack:///src/app/database/migration/common/1707087022764-add-trigger-test-strategy.ts:12:13)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/dist/packages/backend/node_modules/tslib/tslib.js:166:62)"},"msg":"[Main#main]"}
Migration "AddTriggerTestStrategy1707087022764" failed, error: Cannot create property 'testStrategy' on string '{'
{"level":50,"time":1707996577111,"pid":8,"hostname":"3f7c9e1d2e37","err":{"type":"TypeError","message":"Cannot create property 'testStrategy' on string '{'","stack":"TypeError: Cannot create property 'testStrategy' on string '{'\n    at pieceMetadata (webpack:///src/app/database/migration/common/1707087022764-add-trigger-test-strategy.ts:51:17)\n    at AddTriggerTestStrategy1707087022764.<anonymous> (webpack:///src/app/database/migration/common/1707087022764-add-trigger-test-strategy.ts:12:13)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/dist/packages/backend/node_modules/tslib/tslib.js:166:62)"},"msg":"[Main#main]"}
```

How to fix this problem?
