### ISSUE TITLE
[BUG]: Running self-hosted yet getting asked to upgrade

### ISSUE THREAD

**Issue by NightHawkATL** [activepieces/activepieces#4033]
I just deployed this on my server and I am trying to setup all of the features like API and email and templates and I am only greeted with the upgrade option and no way to prove that it is self-hosted.

My compose is as follows:
```
name: activepieces
services:
  activepieces:
    image: ghcr.io/activepieces/activepieces:0.20.3
    container_name: activepieces
    hostname: activepieces
    privileged: true
    ports:
      - 21080:80
    volumes:
      - /portainer/Files/AppData/Config/activepieces/root:/root/.activepieces
    environment:
      - AP_ENVIRONMENT=prod
      - AP_ENGINE_EXECUTABLE_PATH=dist/packages/engine/main.js
      - AP_WEBHOOK_TIMEOUT_SECONDS=30
      - AP_TRIGGER_DEFAULT_POLL_INTERVAL=5
      - AP_QUEUE_MODE=REDIS
      - AP_QUEUE_UI_ENABLED=true
      - AP_FLOW_WORKER_CONCURRENCY=10
      - AP_ENCRYPTION_KEY=${ENC_KEY}
      - AP_JWT_SECRET=${JWT_SEC}
      - AP_API_KEY=${API_KEY}
      - AP_DB_TYPE=POSTGRES
      - AP_POSTGRES_HOST=postgres
      - AP_POSTGRES_PORT=5432
      - AP_POSTGRES_DATABASE=${POS_DB}
      - AP_POSTGRES_PASSWORD=${POS_PASS}
      - AP_POSTGRES_USERNAME=${POS_USER}
      - AP_EXECUTION_MODE=UNSANDBOXED
      - AP_REDIS_HOST=redis
      - AP_REDIS_PORT=6379
#      - AP_QUEUE_UI_ENABLED=true
      - AP_QUEUE_UI_USERNAME=${UI_USER}
      - AP_QUEUE_UI_PASSWORD=${UI_PASS}
      - AP_FRONTEND_URL=http://10.0.2.24:21080
      - AP_SANDBOX_RUN_TIME_SECONDS=600
      - AP_TELEMETRY_ENABLED=true
      - AP_TEMPLATES_SOURCE_URL="https://cloud.activepieces.com/api/v1/flow-templates"
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
  
  postgres:
    image: 'postgres:14.4'
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POS_DB}
      - POSTGRES_PASSWORD=${POS_PASS}
      - POSTGRES_USER=${POS_USER}
    volumes:
      - /portainer/Files/AppData/Config/activepieces/postgres_data:/var/lib/postgresql/data
  
  redis:
    image: 'redis:7.0.7'
    container_name: redis
    restart: unless-stopped
    volumes:
      - '/portainer/Files/AppData/Config/activepieces/redis_data:/data'
```
