### ISSUE TITLE
[BUG]: Flows and account not migrated after upgrading from 0.20.2 to 0.21.0

### ISSUE THREAD

**Issue by MrMYHuang** [activepieces/activepieces#4528]
**Describe the bug**
I set up my activepieces in a docker-compose.yml file, like this:
```
# ...

    activepieces:
      image: activepieces/activepieces:0.20.2
      privileged: true
      ports:
        - 8892:80
      volumes:
        - ~/.activepieces:/root/.activepieces
      environment:
        - AP_QUEUE_MODE=MEMORY
        - AP_EXECUTION_MODE=SANDBOXED
        - AP_SIGN_UP_ENABLED=true
        - AP_DB_TYPE=SQLITE3
        - AP_TRIGGER_DEFAULT_POLL_INTERVAL=1
        - AP_CLOUD_AUTH_ENABLED=true
        - AP_WEBHOOK_TIMEOUT_SECONDS=300
        - AP_FRONTEND_URL=https://activepieces.example.com
      networks:
        - backend
       
# ...
```
After I update the activepieces version from 0.20.2 to 0.21.0 in docker-compose.yml, then I execute `docker-compose up -d, activepieces`, it starts with the following meesages without errors:
```
{"level":30,"time":1713840979934,"pid":8,"hostname":"4b8720cd2b94","msg":"CreateDefaultPlatform1705967115116 up"}
{"level":30,"time":1713840979936,"pid":8,"hostname":"4b8720cd2b94","msg":"Found 4 standalone projects"}
{"level":30,"time":1713840979944,"pid":8,"hostname":"4b8720cd2b94","msg":"CreateDefaultPlatform1705967115116 up done"}
{"level":30,"time":1713840979970,"pid":8,"hostname":"4b8720cd2b94","name":"AddPlatformForeignKeyToProjectSqlite1709566629593","msg":"up"}
{"level":30,"time":1713840979982,"pid":8,"hostname":"4b8720cd2b94","msg":"MigrateWebhook1709581196563, started"}
{"level":30,"time":1713840979984,"pid":8,"hostname":"4b8720cd2b94","msg":"MigrateWebhook1709581196563, flows migrated 0"}
{"level":30,"time":1713840979985,"pid":8,"hostname":"4b8720cd2b94","msg":"MigrateWebhook1709581196563, flows migrated 0"}
{"level":30,"time":1713840980013,"pid":8,"hostname":"4b8720cd2b94","msg":"MigrateWebhook1709581196563, finished flows 19"}
{"level":30,"time":1713840980047,"pid":8,"hostname":"4b8720cd2b94","name":"seedDevData","msg":"skip: not in development environment"}
{"level":30,"time":1713840981116,"pid":8,"hostname":"4b8720cd2b94","msg":"Adding 0 repeated flows to the queue manager."}
{"level":30,"time":1713840981116,"pid":8,"hostname":"4b8720cd2b94","msg":"Adding 0 renew flows to the queue manager."}
{"level":30,"time":1713840981229,"pid":8,"hostname":"4b8720cd2b94","msg":"Adding 0 flow runs to the queue manager."}
{"level":30,"time":1713840981372,"pid":8,"hostname":"4b8720cd2b94","msg":"Activepieces ce Edition"}
{"level":30,"time":1713840981937,"pid":8,"hostname":"4b8720cd2b94","msg":"Server listening at http://0.0.0.0:3000"}
{"level":30,"time":1713840981937,"pid":8,"hostname":"4b8720cd2b94","msg":"\n             _____   _______   _____  __      __  ______   _____    _____   ______    _____   ______    _____\n    /\\      / ____| |__   __| |_   _| \\ \\    / / |  ____| |  __ \\  |_   _| |  ____|  / ____| |  ____|  / ____|\n   /  \\    | |         | |      | |    \\ \\  / /  | |__    | |__) |   | |   | |__    | |      | |__    | (___\n  / /\\ \\   | |         | |      | |     \\ \\/ /   |  __|   |  ___/    | |   |  __|   | |      |  __|    \\___ \\\n / ____ \\  | |____     | |     _| |_     \\  /    | |____  | |       _| |_  | |____  | |____  | |____   ____) |\n/_/    \\_\\  \\_____|    |_|    |_____|     \\/     |______| |_|      |_____| |______|  \\_____| |______| |_____/\n\nThe application started on https://activepieces.i-guu.com, as specified by the AP_FRONTEND_URL variables.\n    "}
```

Unfortunately, no flow and no account were successfully migrated. Is there any solution? I also tried update from 0.20.2 to 0.25.0, but the result was the same as 0.21.0.
