### ISSUE TITLE
[BUG]: App crashes at runtime due to a missing dependency: write-file-atomic on 0.59.0 & 0.59.1

### ISSUE THREAD

**Issue by nvroot** [activepieces/activepieces#7946]
**Describe the bug**
Deploying the latest version using Docker fails with a MODULE_NOT_FOUND error for the write-file-atomic module. This occurs with both 0.59.0 and 0.59.1.

**To Reproduce**
1. Deploy the latest
2. Try to use & Observe logs 

**Actual behavior**
The application crashes at runtime due to a missing dependency

**Additional context**
```
Node.js v18.20.5
node:internal/modules/cjs/loader:1143
  throw err;
  ^
Error: Cannot find module 'write-file-atomic'
Require stack:
- /usr/src/app/dist/packages/server/api/main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
    at Module._load (node:internal/modules/cjs/loader:981:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at moduleId (webpack:///external%20commonjs%20%22write-file-atomic%22:1:18)
    at n (webpack:///webpack/bootstrap:19:22)
    at moduleId (webpack:///worker/src/lib/cache/cache-state.ts:5:1)
    at n (webpack:///webpack/bootstrap:19:22)
    at moduleId (webpack:///worker/src/lib/piece-manager/development/pieces-builder.ts:10:1)
    at n (webpack:///webpack/bootstrap:19:22) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/src/app/dist/packages/server/api/main.js' ]
}
```

**Comment by AbdulTheActivePiecer** [comment]
Investigating this, thanks for opening the issue.

**Comment by nvroot** [comment]
@AbdulTheActivePiecer 

Used docker-compose:

```
x-default-healthcheck: &default-healthcheck
  interval: 60s
  timeout: 20s
  retries: 5
  start_period: 60s
  start_interval: 5s
services:
  activepieces:
    image: "ghcr.io/activepieces/activepieces:latest"
    container_name: activepieces
    restart: unless-stopped
    environment:
      - AP_API_KEY=change-api-key
      - AP_ENCRYPTION_KEY=change-ecryption-key
      - 'AP_ENGINE_EXECUTABLE_PATH=dist/packages/engine/main.js'
      - AP_ENVIRONMENT=prod
      - AP_EXECUTION_MODE=UNSANDBOXED
      - AP_FRONTEND_URL=https://activepieces.example.com
      - AP_JWT_SECRET=change-jwt-secret
      - AP_POSTGRES_DATABASE=activepieces
      - AP_POSTGRES_HOST=postgres
      - AP_POSTGRES_PASSWORD=changeme
      - AP_POSTGRES_PORT=5432
      - AP_POSTGRES_USERNAME=activepiecesuser
      - AP_REDIS_HOST=redis
      - AP_REDIS_PORT=6379
      - AP_SANDBOX_RUN_TIME_SECONDS=600
      - AP_TELEMETRY_ENABLED=false
      - 'AP_TEMPLATES_SOURCE_URL=${AP_TEMPLATES_SOURCE_URL:-https://cloud.activepieces.com/api/v1/flow-templates}'
      - AP_TRIGGER_DEFAULT_POLL_INTERVAL=5
      - AP_WEBHOOK_TIMEOUT_SECONDS=30
    expose:
      - 80
    networks:
      - proxy
      - activepieces-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80"]
      <<: *default-healthcheck
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=activepieces
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_USER=activepiecesuser
      - POSTGRES_PORT=5432
    volumes:
      - "activepieces-db:/var/lib/postgresql/data"
    networks:
      - activepieces-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      <<: *default-healthcheck
  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - "activepieces-redis:/data"
    networks:
      - activepieces-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      <<: *default-healthcheck
volumes:
  activepieces-redis:
  activepieces-db:
networks:
  activepieces-network:
    name: activepieces-network
    driver: bridge
  proxy:
    external: true

```
